### ISSUE TITLE
Panic Bugs

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#324]
`ratio := new(big.Rat).SetFrac(cutoff.Big(), expectedCollateral.Big())`

```
panic: division by zero

goroutine 179 [running]:
math/big.(*Rat).SetFrac(0xc001d5fbc0, 0xc0396fa020, 0xc0396fa040)
        /home/derrick/.gvm/pkgsets/go1.18.6/global/go1.19/src/math/big/rat.go:307 +0x2c5
go.sia.tech/renterd/autopilot.collateralScore({{0x0}, {0x0, 0x0, 0x0}, {{0xc00338e180, 0x9}, 0x32, {0x9fd0803ce8000000, 0x33b2e3c}, 0x17a0, ...}}, ...)
        portal/vendor/go.sia.tech/renterd/autopilot/hostscore.go:150 +0x28d
go.sia.tech/renterd/autopilot.hostScore({{0x0}, {0x0, 0x0, 0x0}, {{0xc00338e180, 0x9}, 0x32, {0x9fd0803ce8000000, 0x33b2e3c}, 0x17a0, ...}}, ...)
        portal/vendor/go.sia.tech/renterd/autopilot/hostscore.go:20 +0x1a5
go.sia.tech/renterd/autopilot.isUsableHost({{0x0}, {0x0, 0x0, 0x0}, {{0xc00338e180, 0x9}, 0x32, {0x9fd0803ce8000000, 0x33b2e3c}, 0x17a0, ...}}, ...)
        portal/vendor/go.sia.tech/renterd/autopilot/hostfilter.go:212 +0x845
go.sia.tech/renterd/autopilot.(*contractor).candidateHosts(0xc0003b6d20, {0x236d0a0, 0xc00d548fc0}, {0x2374408, 0xc0003780f0}, {0xc0703d4000, 0x149ca, 0x1680a}, 0xc001d62478, 0xc008e86000, ...)
        portal/vendor/go.sia.tech/renterd/autopilot/contractor.go:847 +0x14a7
go.sia.tech/renterd/autopilot.(*contractor).managedFindMinAllowedHostScores(0xc0003b6d20, {0x236d0a0, 0xc00d548fc0}, {0x2374408, 0xc0003780f0}, {0xc0703d4000, 0x149ca, 0x1680a}, 0xc008e86000)
        portal/vendor/go.sia.tech/renterd/autopilot/contractor.go:773 +0x1f0
go.sia.tech/renterd/autopilot.(*contractor).performContractMaintenance(0xc0003b6d20, {0x236d0a0, 0xc00d548fc0}, {0x2374408, 0xc0003780f0})
        portal/vendor/go.sia.tech/renterd/autopilot/contractor.go:171 +0x1145
go.sia.tech/renterd/autopilot.(*Autopilot).Run.func1({0x2374408, 0xc0003780f0})
        portal/vendor/go.sia.tech/renterd/autopilot/autopilot.go:259 +0xcd4
go.sia.tech/renterd/autopilot.(*workerPool).withWorker(0xc0003781b0, 0xc05b59fe90)
        portal/vendor/go.sia.tech/renterd/autopilot/autopilot.go:148 +0x102
go.sia.tech/renterd/autopilot.(*Autopilot).Run(0xc00037a000)
        portal/vendor/go.sia.tech/renterd/autopilot/autopilot.go:206 +0x734
git.lumeweb.com/LumeWeb/portal/renterd.Main.func2()
        portal/renterd/main.go:324 +0x2b
created by git.lumeweb.com/LumeWeb/portal/renterd.Main
        portal/renterd/main.go:324 +0x2a8c
```
`t := time.NewTicker(cl.d / 2)` going negative?

```
panic: non-positive interval for NewTicker

goroutine 10119 [running]:
time.NewTicker(0x0)
        /home/derrick/.gvm/pkgsets/go1.18.6/global/go1.19/src/time/tick.go:24 +0x1aa
go.sia.tech/renterd/worker.(*contractLock).keepaliveLoop(0xc135c6d080)
        portal/vendor/go.sia.tech/renterd/worker/worker.go:1349 +0x4f
created by go.sia.tech/renterd/worker.(*worker).AcquireContract
        portal/vendor/go.sia.tech/renterd/worker/worker.go:1388 +0x6fb
```

**Comment by ChrisSchinnerl** [comment]
Closing this for now since it should be fixed by #329 

Thanks again for reporting!
