### ISSUE TITLE
Slabs suddenly empty

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/renterd#447]
## Describe the bug
Started as  a question [on discord](https://discord.com/channels/809849352516141067/946328563320238190/1123350670855114895).
Today i noticed files i uploaded earlier, a week or so ago, downloads as zero bytes files. In the UI i can see the correct file size and the health checkmarks are green but hovering over them says "excellent health (NaN%)". If i copy the metadata via the ui the "slabs" array is empty. Files i uploaded earlier today works as expected.

I noticed my logs has plenty of lines like
`{"level":"debug","date":"2023-06-26T12:35:37-01:00","component":"autopilot.migrator","msg":"worker: successfully migrated slab 'key:xxxxxxxxxx' (health: 0.65) 57/1110"}`
where the 57/1110 counts up but a lot of those groups ends somewhere early like that and doesn't get to 1110/1110. Im just figuring it should migrate all those slabs if it's started but maybe that's not how it works.

I haven't seen any attempts to migrate slabs since 2023-06-27T16:00:57-01:00, I've gotten no noticeable cpu/disk/network activity since then either and i'm seeing this in the logs:
```
{"level":"info","date":"2023-06-28T05:48:13-01:00","component":"autopilot.migrator","msg":"performing migrations"}
{"level":"debug","date":"2023-06-28T05:48:13-01:00","component":"autopilot.migrator","msg":"0 potential slabs fetched for migration"}
{"level":"debug","date":"2023-06-28T05:48:13-01:00","component":"autopilot.migrator","msg":"0 slabs to migrate"}
```

Also i've noticed in the logs i have two contracts that keep replacing eachother over and over, a few times per hour for days now:
```
{"level":"debug","date":"2023-06-28T05:38:07-01:00","component":"autopilot.contractor","msg":"contract fcid:8c3b4dd46ac71b12f68df33f3f768811f1504af14008de4b0dff56e843d59317 was removed from the contract set, size: 4034920448, reason: truncated"}
{"level":"debug","date":"2023-06-28T05:38:07-01:00","component":"autopilot.contractor","msg":"contract fcid:9466b612165614d4b1fa267df52b029172e994e7ddc41ef8dbd3b7a3170f76c9 was added to the contract set, size: 30396121088"}
{"level":"debug","date":"2023-06-28T05:38:07-01:00","component":"autopilot.contractor","msg":"contractset after maintenance","formed":0,"renewed":0,"refreshed":0,"contracts":50,"added":1,"removed":1}
```

then

```
{"level":"debug","date":"2023-06-28T05:48:13-01:00","component":"autopilot.contractor","msg":"contract fcid:9466b612165614d4b1fa267df52b029172e994e7ddc41ef8dbd3b7a3170f76c9 was removed from the contract set, size: 30396121088, reason: host's score is below minimum"}
{"level":"debug","date":"2023-06-28T05:48:13-01:00","component":"autopilot.contractor","msg":"contract fcid:8c3b4dd46ac71b12f68df33f3f768811f1504af14008de4b0dff56e843d59317 was added to the contract set, size: 4034920448"}
{"level":"debug","date":"2023-06-28T05:48:13-01:00","component":"autopilot.contractor","msg":"contractset after maintenance","formed":0,"renewed":0,"refreshed":0,"contracts":50,"added":1,"removed":1}
```
unsure if that's relevant though.

I've restarted renterd a few times the last few days, to pull in new commits and rebuild, but not when i've known it to be migrating anything and not forcefully.

## Expected behaviour
Files should have slabs and be downloadable.

### General Information
Are you running a fork of `renterd`? No, running version built from 1cff37f now.
Are you on the mainnet or on the testnet? Mainnet

### Renterd Config

Running with the following flags:
`./renterd -http localhost:9780 -bus.gatewayAddr localhost:9781`

Please provide us the following information:

**Autopilot Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9780/api/autopilot/config
{
        "contracts": {
                "set": "autopilot",
                "amount": 50,
                "allowance": "9000000000000000000000000000",
                "period": 6048,
                "renewWindow": 2016,
                "download": 3000000000000,
                "upload": 3000000000000,
                "storage": 11000000000000
        },
        "hosts": {
                "allowRedundantIPs": false,
                "maxDowntimeHours": 1440,
                "scoreOverrides": null
        },
        "wallet": {
                "defragThreshold": 1000
        }
}

```

**Bus Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9780/api/bus/setting/redundancy
{
        "minShards": 10,
        "totalShards": 30
}

curl -u ":[YOUR_PASSWORD]" http://localhost:9780/api/bus/setting/gouging
{
        "hostBlockHeightLeeway": 6,
        "maxContractPrice": "850000000000000000000000",
        "maxDownloadPrice": "3000000000000000000000000000",
        "maxRPCPrice": "2000000000000000000000",
        "maxStoragePrice": "578703703704",
        "maxUploadPrice": "950000000000000000000000000",
        "minAccountExpiry": 86400000000000,
        "minMaxCollateral": "10000000000000000000000000",
        "minMaxEphemeralAccountBalance": "1000000000000000000000000",
        "minPriceTableValidity": 300000000000
}
```

**Contract Set Contracts**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9780/api/bus/contracts/set/autopilot | grep '"id"' | wc -l
50
```

### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.
Here's the last 2000 lines of my renterd.log:
[short.log](https://github.com/SiaFoundation/renterd/files/11891426/short.log)

**Comment by peterjan** [comment]
Hi @multikatt , some of the side effects you are describing are expected behaviour of `renterd`. 

> where the 57/1110 counts up but a lot of those groups ends somewhere early like that and doesn't get to 1110/1110. Im just figuring it should migrate all those slabs if it's started but maybe that's not how it works.

Contracts will flow in and out of your contract set and cause migrations to be recalculated, potentially interrupting an ongoing migration and re-evaluating what needs to be migrated.

> Also i've noticed in the logs i have two contracts that keep replacing each other over and over, a few times per hour for days now:

Coincidentally I've been debugging this for a bit with Chris in the last couple of days, all of the instances we've looked at more closely were all valid cases where larger contracts are thrown out for a particular scoring issue and then float back in. If you have some contracts/hosts that flirt with the threshold what your seeing can occur and shouldn't be an issue per se.

Note that we worked through a couple of hidden issues with`renterd` recently and, depending on how long you've been running `renterd` for, your database might still be "corrupted" in a way that new instances of `renterd` wouldn't be.

We definitely want to look at this closer and investigate. To do so we would need your entire `renterd.log` and ideally a database dump? If that's an option of course, we would understand if this is something you would not be willing to share. I'll shoot you a friend request on Discord. Could you perhaps also edit the issue and add the output of 
`curl -u ":[YOUR_PASSWORD]" http://localhost:9780/api/bus/stats/objects`

**Comment by peterjan** [comment]
This is prevent from happening again in the future by #449 . You can only repair your database using one of those database backups you took. If it's testing data I would not bother and simply delete all objects from before `2023-06-20` or start fresh. Thank you for reporting this issue!

**Comment by multikatt** [comment]
You're so fast! It's data I can replace so no worries. Thanks!

**Comment by multikatt** [comment]
I decided to try using one of the old backups i had after all. First time i tried i just used the main branch of renterd which wiped the slabs right away again. So i checked out your version from the pull request above instead, and put up my old backup again. And this time it didn't wipe it. So to me it seems like it works the way it was intended!

**Comment by peterjan** [comment]
We decided to close out #449 in favour of #450 . Turns out `DisableForeignKeyConstraintWhenMigrating` means something else entirely. Probably best for you to reinstate a backup and run `master` once it's merged.

**Comment by multikatt** [comment]
Ok, saw it was merged now so i've tried that instead. But im being spammed with these errors:
```
goroutine 127060 [running]:
net/http.(*conn).serve.func1()
        /snap/go/current/src/net/http/server.go:1854 +0xbf
panic({0x10bfcc0, 0xc00219bec0})
        /snap/go/current/src/runtime/panic.go:890 +0x263
go.sia.tech/renterd/stores.rawObject.toSlabSlice({0xc001ede400, 0x1, 0x7fcd2b157b08?})
        /home/sia/renterd/stores/metadata.go:339 +0x415
go.sia.tech/renterd/stores.rawObject.convert.func1(0x1, 0x1624)
        /home/sia/renterd/stores/metadata.go:282 +0xa5
go.sia.tech/renterd/stores.rawObject.convert({0xc001ede400?, 0xd, 0x14})
        /home/sia/renterd/stores/metadata.go:305 +0x450
go.sia.tech/renterd/stores.(*SQLStore).Object(0xc003bba450?, {0x15e5130?, 0xc003bba4b0?}, {0xc002aca1f4?, 0xc0006c6f18?})
        /home/sia/renterd/stores/metadata.go:669 +0x4b
go.sia.tech/renterd/bus.(*bus).objectsHandlerGET(0xc0006900b0, {{0x15e4d80, 0xc0067e2660}, 0xc001ea9b00, {0xc009d363a0, 0x1, 0x1}})
        /home/sia/renterd/bus/bus.go:726 +0x1bb
go.sia.tech/jape.Adapt.func1.1({0x15e4d80, 0xc0067e2660}, 0xc001ea9b00)
        /home/sia/go/pkg/mod/go.sia.tech/jape@v0.9.1-0.20230525021720-ecf031ecbffb/server.go:194 +0xf6
net/http.HandlerFunc.ServeHTTP(0x15e5130?, {0x15e4d80?, 0xc0067e2660?}, 0x15d66b8?)
        /snap/go/current/src/net/http/server.go:2122 +0x2f
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc002146840, {0x15e3d90?, 0xc0020aafc0}, 0xc001ea9a00)
        /home/sia/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.39.0/handler.go:213 +0x1231
go.sia.tech/jape.Adapt.func1.2({{0x15e3d90, 0xc0020aafc0}, 0xc001ea9900, {0xc009d363a0, 0x1, 0x1}})
        /home/sia/go/pkg/mod/go.sia.tech/jape@v0.9.1-0.20230525021720-ecf031ecbffb/server.go:197 +0x1a8
go.sia.tech/jape.adaptor.func1({0x15e3d90?, 0xc0020aafc0?}, 0xc002aca1e0?, {0xc009d363a0?, 0x0?, 0xc0006c77a8?})
        /home/sia/go/pkg/mod/go.sia.tech/jape@v0.9.1-0.20230525021720-ecf031ecbffb/server.go:156 +0x6a
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0007fda40, {0x15e3d90, 0xc0020aafc0}, 0xc001ea9900)
        /home/sia/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c
go.sia.tech/jape.BasicAuth.func1.1({0x15e3d90, 0xc0020aafc0}, 0x41e550?)
        /home/sia/go/pkg/mod/go.sia.tech/jape@v0.9.1-0.20230525021720-ecf031ecbffb/server.go:211 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc0006c79a8?, {0x15e3d90?, 0xc0020aafc0?}, 0x2c26b35706c158ec?)
        /snap/go/current/src/net/http/server.go:2122 +0x2f
main.treeMux.ServeHTTP({{0x15de540?, 0xc00214dbc0?}, 0x0?}, {0x15e3d90, 0xc0020aafc0}, 0xc001ea9900)
        /home/sia/renterd/cmd/renterd/web.go:27 +0x29b
main.treeMux.ServeHTTP({{0x15db540?, 0xc000510048?}, 0xc000504630?}, {0x15e3d90, 0xc0020aafc0}, 0xc001ea9900)
        /home/sia/renterd/cmd/renterd/web.go:23 +0x268
net/http.serverHandler.ServeHTTP({0xc003bba180?}, {0x15e3d90, 0xc0020aafc0}, 0xc001ea9900)
        /snap/go/current/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00196fdd0, {0x15e5130, 0xc0020310b0})
        /snap/go/current/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /snap/go/current/src/net/http/server.go:3089 +0x5ed
```

**Comment by peterjan** [comment]
Hi @multikatt , thanks for reporting and testing this out. I believe we overlooked sectors when testing your migration, focussing on there being no slabs. I've drop and re-add an extra constraint that should fix this issue. I've also added a custom error message should your database encounter a corrupted object. I will ping Alex so the UI can handle it appropriately. 

I tested your database locally against the new migration and I think you should be able to download files uploaded after 16/6 again. Let me know though should that not be the case.

**Comment by multikatt** [comment]
I tried restoring a backup from 20/6 which has slabs for files created before 16/6 in them. If possible i would prefer to be able to use that was the bulk of what i've uploaded. When i used the version from https://github.com/SiaFoundation/renterd/pull/449 i could download most of the files, but with the current main i cannot. As i said my data is stuff i have other backups of so no problem if i need to reupload it. But it's just surprising to me the #449 version seem to work.

**Comment by peterjan** [comment]
Just to clarify, did you try `master` or `pj/corrupted-slab` in #462 linked above?
