### ISSUE TITLE
Crashing when aborting upload

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/renterd#491]
## Describe the bug
If I hit ctrl-c when uploading a file via curl renterd crashes with an error like the following:
```
goroutine 4336 [running]:
go.sia.tech/renterd/worker.(*upload).uploadSlab(0xc000ac50e0?, {0x15fc0d0?, 0xc00375df80?}, {0x449865?, 0xc000ac50e0?}, {0xc01ab60000, 0x2800000, 0x2800000}, 0x850000, 0x1, ...)
        /home/sia/renterd/worker/upload.go:669 +0x3d5
created by go.sia.tech/renterd/worker.(*uploadManager).Upload
        /home/sia/renterd/worker/upload.go:322 +0x9b0
```
I run curl using the following command:
`curl -u ":pass" -H "Content-Type: application/octet-stream" -T testfile -X PUT localhost:9780/api/worker/objects/testfile`

## Expected behaviour
Maybe getting an error message or similar but not a hard crash.

### General Information
_Are you running a fork of `renterd`?_
no
_Are you on the mainnet or on the testnet?_
mainnet

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/autopilot/config

{
        "contracts": {
                "set": "autopilot",
                "amount": 50,
                "allowance": "9000000000000000000000000000",
                "period": 6048,
                "renewWindow": 2016,
                "download": 3000000000000,
                "upload": 3000000000000,
                "storage": 11000000000000
        },
        "hosts": {
                "allowRedundantIPs": false,
                "maxDowntimeHours": 336,
                "scoreOverrides": null
        },
        "wallet": {
                "defragThreshold": 1000
        }
}
```

**Bus Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/redundancy
{
        "minShards": 10,
        "totalShards": 30
}

curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/gouging

{
        "hostBlockHeightLeeway": 6,
        "maxContractPrice": "450000000000000000000000",
        "maxDownloadPrice": "2300000000000000000000000000",
        "maxRPCPrice": "2000000000000000000000",
        "maxStoragePrice": "254629629630",
        "maxUploadPrice": "900000000000000000000000000",
        "minAccountExpiry": 86400000000000,
        "minMaxCollateral": "10000000000000000000000000",
        "minMaxEphemeralAccountBalance": "1000000000000000000000000",
        "minPriceTableValidity": 300000000000
}
```
**Contract Set Contracts**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/contracts/set/autopilot | grep '"id"' | wc -l
50
```

### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.

**Comment by ChrisSchinnerl** [comment]
Thanks for reporting! Fix will be merged in a bit.
