### ISSUE TITLE
Worker crashing while uploading files

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#942]
### Current Behavior

```
Using RENTERD_BUS_REMOTE_ADDR environment variable
Using RENTERD_BUS_API_PASSWORD environment variable
Using RENTERD_WORKER_API_PASSWORD environment variable
Using RENTERD_WORKER_ENABLED environment variable
Using RENTERD_WORKER_ID environment variable
Using RENTERD_AUTOPILOT_ENABLED environment variable
2024-02-08T14:39:18Z	INFO	renterd/main.go:430	renterd	{"version": "8955d02", "network": "Zen Testnet", "commit": "8955d02", "buildDate": "2024-02-07T12:46:49Z"}
2024-02-08T14:39:18Z	INFO	renterd/main.go:495	connecting to remote bus at http://renterd-bus:9980/api/bus
2024-02-08T14:39:18Z	INFO	renterd/main.go:601	api: Listening on [::]:9980
2024-02-08T14:39:18Z	INFO	renterd/main.go:605	s3: Listening on [::]:8080
2024-02-08T14:39:18Z	INFO	renterd/main.go:612	bus: Listening on 185.81.56.83:9981
panic: no interaction recorder attached to the context
goroutine 359 [running]:
go.sia.tech/renterd/worker.HostInteractionRecorderFromContext(...)
	/renterd/worker/interactions.go:48
go.sia.tech/renterd/worker.(*host).FetchPriceTable.func1.1({0x1a3bac8, 0xc00020c000}, 0xc000456150?)
	/renterd/worker/host.go:195 +0x305
go.sia.tech/renterd/worker.(*transportPoolV3).withTransportV3(0xc0002d02e0, {0x1a3bac8, 0xc00020c000}, {0x95, 0x77, 0xd, 0x3b, 0x9b, 0xf0, 0x2e, ...}, ...)
	/renterd/worker/rhpv3.go:225 +0x175
go.sia.tech/renterd/worker.(*host).FetchPriceTable.func1(_)
	/renterd/worker/host.go:193 +0xca
go.sia.tech/renterd/worker.(*host).FetchPriceTable(_, {_, _}, _)
	/renterd/worker/host.go:212 +0x1ed
go.sia.tech/renterd/worker.(*priceTable).fetch(_, {_, _}, _)
	/renterd/worker/pricetables.go:160 +0x717
go.sia.tech/renterd/worker.(*priceTables).fetch(_, {_, _}, {0x95, 0x77, 0xd, 0x3b, 0x9b, 0xf0, 0x2e, ...}, ...)
	/renterd/worker/pricetables.go:86 +0x213
go.sia.tech/renterd/worker.(*host).priceTable(_, {_, _}, _)
	/renterd/worker/rhpv3.go:517 +0xf7
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1.1.1(_)
	/renterd/worker/rhpv3.go:286 +0x65
go.sia.tech/renterd/worker.RPCLatestRevision({_, _}, _, {0x97, 0xac, 0xa2, 0x24, 0xe7, 0xc0, 0xfa, ...}, ...)
	/renterd/worker/rhpv3.go:716 +0x228
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1.1({0x1a3bac8?, 0xc00020c000?}, 0xc00051a708?)
	/renterd/worker/rhpv3.go:285 +0xdb
go.sia.tech/renterd/worker.(*transportPoolV3).withTransportV3(0xc0002d02e0, {0x1a3bac8, 0xc00020c000}, {0x95, 0x77, 0xd, 0x3b, 0x9b, 0xf0, 0x2e, ...}, ...)
	/renterd/worker/rhpv3.go:225 +0x175
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1()
	/renterd/worker/rhpv3.go:284 +0xb3
go.sia.tech/renterd/worker.(*account).WithWithdrawal(0xc000441400, {0x1a3bac8?, 0xc00020c000?}, 0xc000547400)
	/renterd/worker/rhpv3.go:446 +0x2b6
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount(_, {_, _}, {0x95, 0x77, 0xd, 0x3b, 0x9b, 0xf0, 0x2e, ...}, ...)
	/renterd/worker/rhpv3.go:282 +0xf9
go.sia.tech/renterd/worker.(*host).FetchRevision(0xc000000780, {_, _}, _)
	/renterd/worker/rhpv3.go:254 +0x1a6
go.sia.tech/renterd/worker.(*uploader).execute(0xc0006a0360, 0xc0002003f0)
	/renterd/worker/uploader.go:205 +0x305
go.sia.tech/renterd/worker.(*uploader).Start(0xc0006a0360)
	/renterd/worker/uploader.go:112 +0x165
created by go.sia.tech/renterd/worker.(*uploadManager).refreshUploaders in goroutine 253
	/renterd/worker/upload.go:757 +0x6ea
```

### Expected Behavior

do not crash

### Steps to Reproduce

1. Upload file via webui (i haven't tested s3)

### Version

8955d02 zen

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu, Kubernetes (https://github.com/artur9010/charts/tree/master/renterd)

### Autopilot Config

{         "contracts": {                 "set": "autopilot",                 "amount": 30,                 "allowance": "143692570742000000000000000000",                 "period": 6048,                 "renewWindow": 2016,                 "download": 7000000000000,                 "upload": 7000000000000,                 "storage": 4000000000000,                 "prune": true         },         "hosts": {                 "allowRedundantIPs": false,                 "maxDowntimeHours": 336,                 "minRecentScanFailures": 10,                 "scoreOverrides": null         } }

### Bus Config

{         "default": "autopilot" } {         "hostBlockHeightLeeway": 6,         "maxContractPrice": "15000000000000000000000000",         "maxDownloadPrice": "3551431456000000000000000000",         "maxRPCPrice": "1000000000000000000000",         "maxStoragePrice": "296076626235",         "maxUploadPrice": "1077494143666666666666666667",         "migrationSurchargeMultiplier": 10,         "minAccountExpiry": 86400000000000,         "minMaxCollateral": "10000000000000000000000000",         "minMaxEphemeralAccountBalance": "1000000000000000000000000",         "minPriceTableValidity": 300000000000 } {         "minShards": 3,         "totalShards": 9 } {         "enabled": true,         "slabBufferMaxSizeSoft": 4294967296 }

### Contract Set Contracts

20

**Comment by artur9010** [comment]
Looks like it still happening, running renterd 16c85e1

```
Using RENTERD_BUS_REMOTE_ADDR environment variable
Using RENTERD_BUS_API_PASSWORD environment variable
Using RENTERD_WORKER_API_PASSWORD environment variable
Using RENTERD_WORKER_ENABLED environment variable
Using RENTERD_WORKER_ID environment variable
Using RENTERD_AUTOPILOT_ENABLED environment variable
2024-02-12T01:35:33Z	INFO	renterd/main.go:430	renterd	{"version": "16c85e1", "network": "Zen Testnet", "commit": "16c85e1", "buildDate": "2024-02-10T11:13:14Z"}
2024-02-12T01:35:33Z	INFO	renterd/main.go:495	connecting to remote bus at http://renterd-bus:9980/api/bus
2024-02-12T01:35:33Z	INFO	renterd/main.go:601	api: Listening on [::]:9980
2024-02-12T01:35:33Z	INFO	renterd/main.go:605	s3: Listening on [::]:8080
2024-02-12T01:35:33Z	INFO	renterd/main.go:612	bus: Listening on 185.81.56.83:9981
2024-02-12T01:35:39Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21240_1_3506176
2024-02-12T01:35:39Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21241_0_4194304
2024-02-12T01:35:39Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21239_0_4194304
2024-02-12T01:35:39Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21233_1_3555328
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21230_11_4194304
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21243_0_4194304
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21237_1_3506176
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21243_1_3080192
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21244_0_4194304
2024-02-12T01:35:40Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21244_1_3047424
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21245_0_4194304
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21245_1_3457024
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21246_0_4194304
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21246_1_3473408
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21247_0_4194304
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21247_1_3489792
2024-02-12T01:35:41Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21248_0_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21248_1_3391488
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21249_0_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21249_1_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21249_2_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21250_0_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21250_1_4194304
2024-02-12T01:35:42Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21250_2_4194304
2024-02-12T01:35:43Z	INFO	s3	s3/s3.go:62	CREATE OBJECT:kubernetesjuicefs-renterd-zen/chunks/0/21/21238_1_3457024
panic: no interaction recorder attached to the context
goroutine 41 [running]:
go.sia.tech/renterd/worker.HostInteractionRecorderFromContext(...)
	/renterd/worker/interactions.go:48
go.sia.tech/renterd/worker.(*host).FetchPriceTable.func1.1({0x1a3ba28, 0xc0001f0460}, 0xc000045590?)
	/renterd/worker/host.go:199 +0x305
go.sia.tech/renterd/worker.(*transportPoolV3).withTransportV3(0xc0002d02e0, {0x1a3ba28, 0xc0001f0460}, {0x63, 0xcc, 0x1, 0xb3, 0xe3, 0x75, 0xfb, ...}, ...)
	/renterd/worker/rhpv3.go:225 +0x175
go.sia.tech/renterd/worker.(*host).FetchPriceTable.func1(_)
	/renterd/worker/host.go:197 +0xca
go.sia.tech/renterd/worker.(*host).FetchPriceTable(_, {_, _}, _)
	/renterd/worker/host.go:216 +0x1ed
go.sia.tech/renterd/worker.(*priceTable).fetch(_, {_, _}, _)
	/renterd/worker/pricetables.go:160 +0x717
go.sia.tech/renterd/worker.(*priceTables).fetch(_, {_, _}, {0x63, 0xcc, 0x1, 0xb3, 0xe3, 0x75, 0xfb, ...}, ...)
	/renterd/worker/pricetables.go:86 +0x213
go.sia.tech/renterd/worker.(*host).priceTable(_, {_, _}, _)
	/renterd/worker/rhpv3.go:517 +0xf7
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1.1.1(_)
	/renterd/worker/rhpv3.go:286 +0x65
go.sia.tech/renterd/worker.RPCLatestRevision({_, _}, _, {0x17, 0xd5, 0x46, 0x55, 0xca, 0x2b, 0x69, ...}, ...)
	/renterd/worker/rhpv3.go:716 +0x228
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1.1({0x1a3ba28?, 0xc0001f0460?}, 0xc0001341b0?)
	/renterd/worker/rhpv3.go:285 +0xdb
go.sia.tech/renterd/worker.(*transportPoolV3).withTransportV3(0xc0002d02e0, {0x1a3ba28, 0xc0001f0460}, {0x63, 0xcc, 0x1, 0xb3, 0xe3, 0x75, 0xfb, ...}, ...)
	/renterd/worker/rhpv3.go:225 +0x175
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount.func1()
	/renterd/worker/rhpv3.go:284 +0xb3
go.sia.tech/renterd/worker.(*account).WithWithdrawal(0xc00014a080, {0x1a3ba28?, 0xc0001f0460?}, 0xc00054f400)
	/renterd/worker/rhpv3.go:446 +0x2b6
go.sia.tech/renterd/worker.(*host).fetchRevisionWithAccount(_, {_, _}, {0x63, 0xcc, 0x1, 0xb3, 0xe3, 0x75, 0xfb, ...}, ...)
	/renterd/worker/rhpv3.go:282 +0xf9
go.sia.tech/renterd/worker.(*host).FetchRevision(0xc00069e000, {_, _}, _)
	/renterd/worker/rhpv3.go:254 +0x1a6
go.sia.tech/renterd/worker.(*uploader).execute(0xc000136480, 0xc0002a20e0)
	/renterd/worker/uploader.go:205 +0x305
go.sia.tech/renterd/worker.(*uploader).Start(0xc000136480)
	/renterd/worker/uploader.go:112 +0x165
created by go.sia.tech/renterd/worker.(*uploadManager).refreshUploaders in goroutine 68
	/renterd/worker/upload.go:756 +0x6ea
```
