### ISSUE TITLE
ui: client side error when I move my mouse over file health stat

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#997]
### Current Behavior

```
TypeError: Cannot read properties of undefined (reading 'map')
    at c (_app-4c0390b9b25b3f6b.js:17:61722)
    at ak (framework-7e58418f45871195.js:9:60902)
    at up (framework-7e58418f45871195.js:9:72784)
    at i (framework-7e58418f45871195.js:9:120316)
    at oD (framework-7e58418f45871195.js:9:99072)
    at framework-7e58418f45871195.js:9:98939
    at oO (framework-7e58418f45871195.js:9:98946)
    at oE (framework-7e58418f45871195.js:9:95698)
    at oP (framework-7e58418f45871195.js:9:96087)
    at r8 (framework-7e58418f45871195.js:9:44812)
```

![image](https://github.com/SiaFoundation/renterd/assets/4835677/5225620a-7e2b-4242-9aa8-f5701acd0b34)

### Expected Behavior

x

### Steps to Reproduce

1. Upload a file
2. Move a cursor over file health, it will start loading slab stats and then crash

### Version

3f09191

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Kubernetes, https://github.com/artur9010/charts/tree/master/renterd

### Autopilot Config

probably not necessary

### Bus Config

probably not necessary

### Contract Set Contracts

probably not necessary

**Comment by ChrisSchinnerl** [comment]
Fixed by https://github.com/SiaFoundation/web/pull/511
